# [Menu](#Menú)

* [Ejercicio 1](#Ejercicio.1)
* [Ejercicio 2](#Ejercicio.2)
* [Ejercicio 3](#Ejercicio.3)

### Ejercicio.1
### [Menú](#Menu) | [siguiente](#Ejercicio.2)

Un criminólogo realizó una investigación para determinar si la incidencia de ciertos tipos de delitos varía de una parte de una gran ciudad a otra. Los crímenes específicos de interés eran el asalto, el robo de casas, el hurto y el homicidio. La siguiente tabla muestra el número de delitos cometidos en cuatro áreas de la ciudad durante un año.

¿A partir de estos datos podemos concluir, a un nivel de significancia de 0.01, que la ocurrencia de estos tipos de delitos depende del distrito de la ciudad?

In [3]:
import pandas as pd

# Datos de la tabla
data = {
    'Tipo de crimen': ['Asalto', 'Robo de casas', 'Hurto', 'Homicidio'],
    'Distrito 1': [162, 310, 258, 280],
    'Distrito 2': [118, 196, 193, 175],
    'Distrito 3': [451, 996, 458, 390],
    'Distrito 4': [18, 25, 10, 19]
}

# Crear un DataFrame
df = pd.DataFrame(data)

# Mostrar la tabla
print(df)

  Tipo de crimen  Distrito 1  Distrito 2  Distrito 3  Distrito 4
0         Asalto         162         118         451          18
1  Robo de casas         310         196         996          25
2          Hurto         258         193         458          10
3      Homicidio         280         175         390          19


In [1]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos de la tabla
data = {
    'Asalto': [162, 310, 258, 280],
    'Robo de casas': [118, 196, 193, 175],
    'Hurto': [451, 996, 458, 390],
    'Homicidio': [18, 25, 10, 19]
}

# Crear un DataFrame
df = pd.DataFrame(data, index=['Distrito 1', 'Distrito 2', 'Distrito 3', 'Distrito 4'])

# Realizar la prueba Chi-cuadrado
chi2, p, dof, expected = chi2_contingency(df)

# Resultados
print(f"Estadístico Chi-cuadrado: {chi2:.4f}")
print(f"P-valor: {p:.4f}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(np.round(expected, 2))

# Nivel de significancia
alpha = 0.01

# Conclusión
if p < alpha:
    print("Rechazamos la hipótesis nula: la ocurrencia de delitos depende del distrito.")
else:
    print("No rechazamos la hipótesis nula: la ocurrencia de delitos no depende del distrito.")


Estadístico Chi-cuadrado: 124.5297
P-valor: 0.0000
Grados de libertad: 9
Frecuencias esperadas:
[[186.37 125.85 423.49  13.29]
 [379.96 256.57 863.38  27.09]
 [228.67 154.41 519.61  16.3 ]
 [214.99 145.17 488.51  15.33]]
Rechazamos la hipótesis nula: la ocurrencia de delitos depende del distrito.


### Ejercicio.2
### [Anterior](#Ejercicio.1) | [Menú](#Menu) | [siguiente](#Ejercicio.3)

10.90 De acuerdo con un estudio de la Universidad Johns Hopkins, publicado en American Journal of Public Health, las viudas viven más que los viudos. Considera los siguientes datos reunidos de supervivencia de 100 viudas y 100 viudos después de la muerte del cónyuge:

Con un nivel de significancia de 0.05, ¿podemos concluir que las proporciones de viudas y viudos son iguales con respecto a los diferentes períodos que un cónyuge sobrevive luego de la muerte de su compañero?

In [6]:
import pandas as pd

# Datos de la tabla
datos = {
    'Años vividos': ['Menos de 5', 'De 5 a 10', 'Más de 10'],
    'Viuda': [25, 42, 33],
    'Viudo': [39, 40, 21]
}

# Crear un DataFrame
df = pd.DataFrame(datos)

# Mostrar la tabla
print(df)


  Años vividos  Viuda  Viudo
0   Menos de 5     25     39
1    De 5 a 10     42     40
2    Más de 10     33     21


In [12]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos
data_10_90 = np.array([[25, 39], 
                       [30, 42], 
                       [33, 21]])

# Crear DataFrame
df_10_90 = pd.DataFrame(data_10_90, columns=['Viuda', 'Viudo'], 
                        index=['Menos de 5 años', '5 a 10 años', 'Más de 10 años'])

# Prueba de chi-cuadrado
chi2_90, p_90, dof_90, expected_90 = chi2_contingency(data_10_90)

# Resultados
alpha = 0.05
print("\nResultados de la prueba de chi-cuadrado para 10.90:")
print(f"Estadístico Chi-cuadrado: {chi2_90:.4f}")
print(f"Valor p: {p_90:.4f}")
print(f"Grados de libertad: {dof_90}")
print(f"Valores esperados: \n{expected_90}")

# Conclusión
if p_90 < alpha:
    print("\nSe rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de viudas y viudos.")
else:
    print("\nNo se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de viudas y viudos.")



Resultados de la prueba de chi-cuadrado para 10.90:
Estadístico Chi-cuadrado: 6.7341
Valor p: 0.0345
Grados de libertad: 2
Valores esperados: 
[[29.64210526 34.35789474]
 [33.34736842 38.65263158]
 [25.01052632 28.98947368]]

Se rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de viudas y viudos.


### Ejercicio.3
### [Anterior](#Ejercicio.2) | [Menú](#Menu) | [siguiente](#Ejercicio.3)

10.91 Las siguientes respuestas respecto al nivel de vida en el momento en que se aplicó una encuesta de opinión independiente a 1000 familias, comparadas con sus respuestas sobre su nivel de vida del año anterior, parecen coincidir con los resultados de un estudio publicado en Across the Board (junio de 1981):

Pruebe la hipótesis de que las proporciones de familias dentro de cada nivel de vida son iguales para cada uno de los cuatro periodos. Utilice un valor P.

In [13]:
import pandas as pd

# Crear la tabla de datos
data = {
    'Periodo': ['1980-Enc', '1980-May', '1980-Sept', '1981-Enc'],
    'Un poco mejor': [72, 63, 47, 40],
    'Igual': [144, 135, 100, 105],
    'No tan bueno': [84, 102, 53, 55],
    'Total': [300, 300, 200, 200]
}

# Crear el DataFrame
df = pd.DataFrame(data).set_index('Periodo')

# Mostrar la tabla
print("Tabla de resultados de la encuesta:")
print(df)

Tabla de resultados de la encuesta:
           Un poco mejor  Igual  No tan bueno  Total
Periodo                                             
1980-Enc              72    144            84    300
1980-May              63    135           102    300
1980-Sept             47    100            53    200
1981-Enc              40    105            55    200


In [14]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos
data_10_91 = np.array([[72, 144, 135],  
                       [63, 135, 120],  
                       [47, 100, 75],   
                       [40, 105, 55]])  

# Crear DataFrame
df_10_91 = pd.DataFrame(data_10_91, columns=['Mejor', 'Igual', 'No tan bueno'], 
                        index=['1980 Ene.', '1980 May.', '1980 Sept.', '1981 Ene.'])

# Prueba de chi-cuadrado
chi2_91, p_91, dof_91, expected_91 = chi2_contingency(data_10_91)

# Resultados
alpha = 0.05
print("\nResultados de la prueba de chi-cuadrado para 10.91:")
print(f"Estadístico Chi-cuadrado: {chi2_91:.4f}")
print(f"Valor p: {p_91:.4f}")
print(f"Grados de libertad: {dof_91}")
print(f"Valores esperados: \n{expected_91}")

# Conclusión
if p_91 < alpha:
    print("\nSe rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.")
else:
    print("\nNo se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.")



Resultados de la prueba de chi-cuadrado para 10.91:
Estadístico Chi-cuadrado: 9.4081
Valor p: 0.1519
Grados de libertad: 6
Valores esperados: 
[[ 71.42254812 155.71402383 123.86342805]
 [ 64.7076077  141.07424381 112.21814849]
 [ 45.17323556  98.48579285  78.34097159]
 [ 40.69660862  88.72593951  70.57745188]]

No se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.
