# [Menu](Menú)

* [EJEMPLO 1](#EJEMPLO.1)
* [EJEMPLO 2](#EJEMPLO.2)
* [EJEMPLO 3](#EJEMPLO.3)
* [EJEMPLO 4](#EJEMPLO.4)
* [EJEMPLO 5](#EJEMPLO.5)
* [EJEMPLO 6](#EJEMPLO.6)
* [EJEMPLO 7](#EJEMPLO.7)
* [EJEMPLO 8](#EJEMPLO.8)
* [EJEMPLO 9](#EJEMPLO.9)


 ### Ejemplo1
 ### [Menú](#Menu) | [siguiente](#Ejemplo.2)

Un criminólogo realizó una investigación para determinar si la incidencia de ciertos tipos de delitos varía de una parte de una gran ciudad a otra. Los crímenes específicos de interés eran el asalto, el robo de casas, el hurto y el homicidio. La siguiente tabla muestra el número de delitos cometidos en cuatro áreas de la ciudad durante un año.

¿A partir de estos datos podemos concluir, a un nivel de significancia de 0.01, que la ocurrencia de estos tipos de delitos depende del distrito de la ciudad?

In [1]:
import pandas as pd

# Datos de la tabla
data = {
    'Tipo de crimen': ['Asalto', 'Robo de casas', 'Hurto', 'Homicidio'],
    'Distrito 1': [162, 310, 258, 280],
    'Distrito 2': [118, 196, 193, 175],
    'Distrito 3': [451, 996, 458, 390],
    'Distrito 4': [18, 25, 10, 19]
}

# Crear un DataFrame
df = pd.DataFrame(data)

# Mostrar la tabla
print(df)

  Tipo de crimen  Distrito 1  Distrito 2  Distrito 3  Distrito 4
0         Asalto         162         118         451          18
1  Robo de casas         310         196         996          25
2          Hurto         258         193         458          10
3      Homicidio         280         175         390          19


In [2]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos de la tabla
data = {
    'Asalto': [162, 310, 258, 280],
    'Robo de casas': [118, 196, 193, 175],
    'Hurto': [451, 996, 458, 390],
    'Homicidio': [18, 25, 10, 19]
}

# Crear un DataFrame
df = pd.DataFrame(data, index=['Distrito 1', 'Distrito 2', 'Distrito 3', 'Distrito 4'])

# Realizar la prueba Chi-cuadrado
chi2, p, dof, expected = chi2_contingency(df)

# Resultados
print(f"Estadístico Chi-cuadrado: {chi2:.4f}")
print(f"P-valor: {p:.4f}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(np.round(expected, 2))

# Nivel de significancia
alpha = 0.01

# Conclusión
if p < alpha:
    print("Rechazamos la hipótesis nula: la ocurrencia de delitos depende del distrito.")
else:
    print("No rechazamos la hipótesis nula: la ocurrencia de delitos no depende del distrito.")

Estadístico Chi-cuadrado: 124.5297
P-valor: 0.0000
Grados de libertad: 9
Frecuencias esperadas:
[[186.37 125.85 423.49  13.29]
 [379.96 256.57 863.38  27.09]
 [228.67 154.41 519.61  16.3 ]
 [214.99 145.17 488.51  15.33]]
Rechazamos la hipótesis nula: la ocurrencia de delitos depende del distrito.


 ### Ejemplo 2
 ### [Anterior](#Ejemplo.1) | [Menú](#Menu) | [siguiente](#Ejemplo.3)

10.90 De acuerdo con un estudio de la Universidad Johns Hopkins, publicado en American Journal of Public Health, las viudas viven más que los viudos. Considera los siguientes datos reunidos de supervivencia de 100 viudas y 100 viudos después de la muerte del cónyuge:

Con un nivel de significancia de 0.05, ¿podemos concluir que las proporciones de viudas y viudos son iguales con respecto a los diferentes períodos que un cónyuge sobrevive luego de la muerte de su compañero?

In [3]:
import pandas as pd

# Datos de la tabla
datos = {
    'Años vividos': ['Menos de 5', 'De 5 a 10', 'Más de 10'],
    'Viuda': [25, 42, 33],
    'Viudo': [39, 40, 21]
}

# Crear un DataFrame
df = pd.DataFrame(datos)

# Mostrar la tabla
print(df)

  Años vividos  Viuda  Viudo
0   Menos de 5     25     39
1    De 5 a 10     42     40
2    Más de 10     33     21


In [4]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos
data_10_90 = np.array([[25, 39], 
                       [30, 42], 
                       [33, 21]])

# Crear DataFrame
df_10_90 = pd.DataFrame(data_10_90, columns=['Viuda', 'Viudo'], 
                        index=['Menos de 5 años', '5 a 10 años', 'Más de 10 años'])

# Prueba de chi-cuadrado
chi2_90, p_90, dof_90, expected_90 = chi2_contingency(data_10_90)

# Resultados
alpha = 0.05
print("\nResultados de la prueba de chi-cuadrado para 10.90:")
print(f"Estadístico Chi-cuadrado: {chi2_90:.4f}")
print(f"Valor p: {p_90:.4f}")
print(f"Grados de libertad: {dof_90}")
print(f"Valores esperados: \n{expected_90}")

# Conclusión
if p_90 < alpha:
    print("\nSe rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de viudas y viudos.")
else:
    print("\nNo se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de viudas y viudos.")


Resultados de la prueba de chi-cuadrado para 10.90:
Estadístico Chi-cuadrado: 6.7341
Valor p: 0.0345
Grados de libertad: 2
Valores esperados: 
[[29.64210526 34.35789474]
 [33.34736842 38.65263158]
 [25.01052632 28.98947368]]

Se rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de viudas y viudos.


 ### Ejemplo 3
 ### [Anterior](#Ejemplo.2) | [Menú](#Menu) | [siguiente](#Ejemplo.4)

10.91 Las siguientes respuestas respecto al nivel de vida en el momento en que se aplicó una encuesta de opinión independiente a 1000 familias, comparadas con sus respuestas sobre su nivel de vida del año anterior, parecen coincidir con los resultados de un estudio publicado en Across the Board (junio de 1981):

Pruebe la hipótesis de que las proporciones de familias dentro de cada nivel de vida son iguales para cada uno de los cuatro periodos. Utilice un valor P.

In [8]:
import pandas as pd

# Crear la tabla de datos
data = {
    'Periodo': ['1980-Enc', '1980-May', '1980-Sept', '1981-Enc'],
    'Un poco mejor': [72, 63, 47, 40],
    'Igual': [144, 135, 100, 105],
    'No tan bueno': [84, 102, 53, 55],
    'Total': [300, 300, 200, 200]
}

# Crear el DataFrame
df = pd.DataFrame(data).set_index('Periodo')

# Mostrar la tabla
print("Tabla de resultados de la encuesta:")
print(df)

Tabla de resultados de la encuesta:
           Un poco mejor  Igual  No tan bueno  Total
Periodo                                             
1980-Enc              72    144            84    300
1980-May              63    135           102    300
1980-Sept             47    100            53    200
1981-Enc              40    105            55    200


In [7]:
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

# Datos
data_10_91 = np.array([[72, 144, 135],  
                       [63, 135, 120],  
                       [47, 100, 75],   
                       [40, 105, 55]])  

# Crear DataFrame
df_10_91 = pd.DataFrame(data_10_91, columns=['Mejor', 'Igual', 'No tan bueno'], 
                        index=['1980 Ene.', '1980 May.', '1980 Sept.', '1981 Ene.'])

# Prueba de chi-cuadrado
chi2_91, p_91, dof_91, expected_91 = chi2_contingency(data_10_91)

# Resultados
alpha = 0.05
print("\nResultados de la prueba de chi-cuadrado para 10.91:")
print(f"Estadístico Chi-cuadrado: {chi2_91:.4f}")
print(f"Valor p: {p_91:.4f}")
print(f"Grados de libertad: {dof_91}")
print(f"Valores esperados: \n{expected_91}")

# Conclusión
if p_91 < alpha:
    print("\nSe rechaza la hipótesis nula. Hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.")
else:
    print("\nNo se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.")


Resultados de la prueba de chi-cuadrado para 10.91:
Estadístico Chi-cuadrado: 9.4081
Valor p: 0.1519
Grados de libertad: 6
Valores esperados: 
[[ 71.42254812 155.71402383 123.86342805]
 [ 64.7076077  141.07424381 112.21814849]
 [ 45.17323556  98.48579285  78.34097159]
 [ 40.69660862  88.72593951  70.57745188]]

No se puede rechazar la hipótesis nula. No hay una diferencia significativa entre las proporciones de familias en los diferentes niveles de vida.


 ### Ejemplo 4
 ### [Anterior](#Ejemplo.3) | [Menú](#Menu) | [siguiente](#Ejemplo.5)

Se lleva a cabo una encuesta en Indiana, Kentucky y Ohio para determinar la postura de los votantes respecto al transporte escolar. Un grupo de 200 votantes de cada uno de estos estados.

In [9]:
import pandas as pd
import scipy.stats as stats

# Crear un DataFrame con los datos
data = {
    'Estado': ['Indiana', 'Kentucky', 'Ohio'],
    'Apoya': [82, 107, 93],
    'No apoya': [97, 66, 74],
    'Indeciso': [21, 27, 33]
}
df = pd.DataFrame(data)
# Convertir los datos en una tabla de contingencia
contingencia = df[['Apoya', 'No apoya', 'Indeciso']].T
contingencia.columns = df['Estado']
print("Tabla de contingencia:")
print(contingencia)
# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = stats.chi2_contingency(contingencia)
# Mostrar los resultados
print("\nResultados de la prueba de chi-cuadrado:")
print(f"Chi-cuadrado: {chi2}")
print(f"P-valor: {p}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(expected)
# Interpretar el p-valor
alpha = 0.05
if p < alpha:
    print("\nSe rechaza la hipótesis nula: hay una relación significativa entre los estados y la postura del votante.")
else:
    print("\nNo se rechaza la hipótesis nula: no hay una relación significativa entre los estados y la postura del votante.")

Tabla de contingencia:
Estado    Indiana  Kentucky  Ohio
Apoya          82       107    93
No apoya       97        66    74
Indeciso       21        27    33

Resultados de la prueba de chi-cuadrado:
Chi-cuadrado: 12.564054223898015
P-valor: 0.013614527755573072
Grados de libertad: 4
Frecuencias esperadas:
[[94. 94. 94.]
 [79. 79. 79.]
 [27. 27. 27.]]

Se rechaza la hipótesis nula: hay una relación significativa entre los estados y la postura del votante.


 ### Ejemplo 5
 ### [Anterior](#Ejemplo.4) | [Menú](#Menu) | [siguiente](#Ejemplo.6)

Se lleva a cabo una investigación en dos ciudades de Virginia para determinar la opinión de los votantes respecto a dos candidatos a la gubernatura en una elección próxima.

A un nivel de significancia de 0.05 pruebe la hipótesis nula de que las proporciones de votantes que están a favor del candidato A, a favor del candidato B o que están indecisos son las mismas para cada ciudad.

In [10]:
import pandas as pd
import scipy.stats as stats

# Crear un DataFrame con los datos
data = {
    'Ciudad': ['Richmond', 'Norfolk'],
    'A favor de A': [204, 229],
    'A favor de B': [211, 198],
    'Indeciso': [85, 73]  # Suponiendo que los indecisos son los restantes
}
df = pd.DataFrame(data)
# Convertir los datos en una tabla de contingencia
contingencia = df[['A favor de A', 'A favor de B', 'Indeciso']].T
contingencia.columns = df['Ciudad']
print("Tabla de contingencia:")
print(contingencia)
# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = stats.chi2_contingency(contingencia)
# Mostrar los resultados
print("\nResultados de la prueba de chi-cuadrado:")
print(f"Chi-cuadrado: {chi2}")
print(f"P-valor: {p}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(expected)
# Interpretar el p-valor
alpha = 0.05
if p < alpha:
    print("\nSe rechaza la hipótesis nula: hay una relación significativa entre la ciudad y la opinión del votante.")
else:
    print("\nNo se rechaza la hipótesis nula: no hay una relación significativa entre la ciudad y la opinión del votante.")

Tabla de contingencia:
Ciudad        Richmond  Norfolk
A favor de A       204      229
A favor de B       211      198
Indeciso            85       73

Resultados de la prueba de chi-cuadrado:
Chi-cuadrado: 2.7680133529054336
P-valor: 0.2505725758535793
Grados de libertad: 2
Frecuencias esperadas:
[[216.5 216.5]
 [204.5 204.5]
 [ 79.   79. ]]

No se rechaza la hipótesis nula: no hay una relación significativa entre la ciudad y la opinión del votante.


 ### Ejemplo 6
 ### [Anterior](#Ejemplo.5) | [Menú](#Menu) | [siguiente](#Ejemplo.7)

En un estudio para estimar la proporción de esposas que de manera regular ven telenovelas se encuentra que 52 de 200 esposas en Denver 31 de 150 en Phoenix y 37 de 150 en Rochester ven al menos una telenovela. Utilice un nivel de significancia de 0.05 para probar la hipótesis de que no hay diferencia entre las proporciones verdaderas de esposas que ven telenovelas en esas tres ciudades funcionario actual para la próxima elección es de 0.58.

El filete ribeye promedio en el restaurante Longhorn Steak pesa al menos 340 gramos.

In [11]:
import pandas as pd
import scipy.stats as stats

# Datos
ciudades = ['Denver', 'Phoenix', 'Rochester']
total_esposas = [200, 150, 150]
ven_telenovelas = [52, 31, 37]

# Crear un DataFrame
df = pd.DataFrame({
    'Ciudad': ciudades,
    'Total': total_esposas,
    'Ven Telenovelas': ven_telenovelas,
    'No Ven Telenovelas': [total - ven for total, ven in zip(total_esposas, ven_telenovelas)]})

# Convertir los datos en una tabla de contingencia
contingencia = df[['Ven Telenovelas', 'No Ven Telenovelas']].T
contingencia.columns = df['Ciudad']
print("Tabla de contingencia:")
print(contingencia)

# Realizar la prueba de chi-cuadrado
chi2, p, dof, expected = stats.chi2_contingency(contingencia)

# Mostrar los resultados
print("\nResultados de la prueba de chi-cuadrado:")
print(f"Chi-cuadrado: {chi2}")
print(f"P-valor: {p}")
print(f"Grados de libertad: {dof}")
print("Frecuencias esperadas:")
print(expected)

# Interpretar el p-valor
alpha = 0.05
if p < alpha:
    print("\nSe rechaza la hipótesis nula: hay una diferencia significativa entre las proporciones.")
else:
    print("\nNo se rechaza la hipótesis nula: no hay diferencia significativa entre las proporciones.")

Tabla de contingencia:
Ciudad              Denver  Phoenix  Rochester
Ven Telenovelas         52       31         37
No Ven Telenovelas     148      119        113

Resultados de la prueba de chi-cuadrado:
Chi-cuadrado: 1.3888888888888886
P-valor: 0.4993517885992763
Grados de libertad: 2
Frecuencias esperadas:
[[ 48.  36.  36.]
 [152. 114. 114.]]

No se rechaza la hipótesis nula: no hay diferencia significativa entre las proporciones.


 ### Ejemplo 7
 ### [Anterior](#Ejemplo.6) | [Menú](#Menu) | [siguiente](#Ejemplo.8)

Una muestra aleatoria de 200 hombres casados, todos jubilados, se clasificó de acuerdo con la educación y el número de hijos:

In [12]:
import pandas as pd

data = [
    [14, 37, 32], 
    [19, 42, 17], 
    [12, 17, 10] 
]

df = pd.DataFrame(data, 
                  index=["Primaria", "Secundaria", "Universidad"],
                  columns=["0-1 hijos", "2-3 hijos", "Más de 3"])

print("10.88: Educación vs Número de hijos (n=200)")
print(df)

10.88: Educación vs Número de hijos (n=200)
             0-1 hijos  2-3 hijos  Más de 3
Primaria            14         37        32
Secundaria          19         42        17
Universidad         12         17        10


In [14]:
import numpy as np
from scipy.stats import chi2_contingency

observed = np.array([[14,37,32], [19,42,17], [12,17,10]])
chi2_stat, p, dof, expected = chi2_contingency(observed)
print(f"Chi² = {chi2_stat:.2f}, p = {p:.4f}, gl = {dof}")
print("Rechazar H₀" if p < 0.05 else "No rechazar H₀")

Chi² = 7.46, p = 0.1133, gl = 4
No rechazar H₀


 ### Ejemplo 8
 ### [Anterior](#Ejemplo.7) | [Menú](#Menu) | [siguiente](#Ejemplo.9)

La enfermeria de una universidad realizó ur experimento para determinar el grado de alivio que brindan tres jarabes para la tos. Cada jarabe se probó en 50 estudiantes y se registraron los siguientes datos:

In [15]:
import pandas as pd

data = [
    [11, 13, 9],
    [32, 28, 27],
    [7, 9, 14]
]

df = pd.DataFrame(
    data,
    index=["Sin alivio", "Cierto alivio", "Alivio completo"],
    columns=["MyQuil", "Robitussin", "Triaminic"]
)

print("10.92: Efectividad de jarabes para la tos (n=150)")
print(df)

10.92: Efectividad de jarabes para la tos (n=150)
                 MyQuil  Robitussin  Triaminic
Sin alivio           11          13          9
Cierto alivio        32          28         27
Alivio completo       7           9         14


In [16]:
import numpy as np
from scipy.stats import chi2_contingency

observed = np.array([[11,13,9], [32,28,27], [7,9,14]])
chi2_stat, p, dof, expected = chi2_contingency(observed)
print(f"Chi² = {chi2_stat:.2f}, p = {p:.4f}, gl = {dof}")
print("Rechazar H₀" if p < 0.05 else "No rechazar H₀")

Chi² = 3.81, p = 0.4323, gl = 4
No rechazar H₀


 ### Ejemplo 9
 ### [Anterior](#EJEMPLO.8) | [Menú](#Menu) | [siguiente](#EJEMPLO.9)

10.93 Para determinar las posturas actuales acerca de rezar en escuelas públicas se llevó a cabo una investigación en 4 condados de Virginia, En la siguiente tabla se presentan las opiniones de 200 padres del condado de 'Craig, de 150 padres del condado de Giles, de 100 padres del condado de Franklin y de 100 padres de condado de Montgomery:

In [17]:
import pandas as pd

data = [
    [65, 66, 40, 34],
    [42, 30, 33, 42],
    [93, 54, 27, 24]
]

df = pd.DataFrame(
    data,
    index=["A favor", "En contra", "Sin opinión"],
    columns=["Craig", "Giles", "Franklin", "Montgomery"]
)

print("10.93: Opiniones sobre rezar en escuelas (n=550)")
print(df)

10.93: Opiniones sobre rezar en escuelas (n=550)
             Craig  Giles  Franklin  Montgomery
A favor         65     66        40          34
En contra       42     30        33          42
Sin opinión     93     54        27          24


In [18]:
import numpy as np
from scipy.stats import chi2_contingency

observed = np.array([[65,66,40,34], [42,30,33,42], [93,54,27,24]])
chi2_stat, p, dof, expected = chi2_contingency(observed)
print(f"Chi² = {chi2_stat:.2f}, p = {p:.4f}, gl = {dof}")
print("Rechazar H₀" if p < 0.05 else "No rechazar H₀")

Chi² = 31.10, p = 0.0000, gl = 6
Rechazar H₀


### REFERENCIAS

PROBABILIDAD Y ESTADISTICA PARA INGENIERIA Y CIENCIAS(Walpole-Myers-myers)
- https://vereniciafunez94hotmail.wordpress.com/wp-content/uploads/2014/08/8va-probabilidad-y-estadistica-para-ingenier-walpole_8.pdf 


pag.
 382-386